name: "🐞 Report a Bug"
description: Create an issue if something does not work as expected.
labels: ["Type/Bug"]
body:
  - type: textarea
    id: background
    attributes:
      label: Description
      description: Please share a clear and concise description of the problem.
      placeholder: Description
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: List the steps you followed when you encountered the issue.
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Version
      description: Enter product/component version.
    validations:
      required: true
  - type: textarea
    id: environment
    attributes:
      label: Environment Details (with versions)
      description: Mention the environment details (OS, Database, Userstore, etc..) that the product is running on.
    validations:
      required: false
  - type: checkboxes
    id: developer-checklist
    attributes:
      label: Developer Checklist
      description: Please confirm the following when closing the issue.
      options:
        - label: Will this change make a behavioural change to the product?
        - label: " ↳ If yes, has it been approved by the team lead?"
        - label: " ↳ If yes, has the label `impact/behavioral-change` been added to this issue?"
        - label: Will this change has a migration impact?
        - label: " ↳ If yes, has the relevant migration labels has been added? ex:`7.2.0-migration`"
        - label: " ↳ If yes, has the relevant migration issues were created and linked?"
        - label: Will this change introduce a new configuration?
        - label: " ↳ If yes, have the new configurations been properly documented?"
